#!/usr/bin/env bash
## clone pysumma and summa and switch to develop branch

git clone -b arbennett:feature/update_summa https://github.com/arbennett/pysumma.git; cd pysumma; pip install .

#cd ..; git clone -b develop https://github.com/NCAR/summa.git
#cd summa; git checkout a3a840b139d80f645fe5acf31d32baad462a899b
cd ..; git clone https://github.com/NCAR/summa.git

## command to edit Makefile flags
#cd build && sed -i 's/$(FC_EXE) $(FLAGS_NOAH) -c $(NOAHMP)/$(FC_EXE) $(FLAGS_NOAH) -c $(NOAHMP) $(INCLUDES)/g' Makefile \
#	 && sed -i 's/$(FC_EXE) $(FLAGS_COMM) -c $(COMM_ALL)/$(FC_EXE) $(FLAGS_COMM) -c $(COMM_ALL) $(INCLUDES)/g' Makefile

## export necessary environment variables specified in Makefile
export F_MASTER=/home/jovyan/summa
export FC=gfortran
export FC_EXE=/usr/bin/gfortran-6
export INCLUDES='-I/usr/include'
export LIBRARIES='-L/usr/lib -lnetcdff -lblas -llapack'

## build from Makefile
make -f ${F_MASTER}/build/Makefile

# Install the JupyterLab dask-labextension
jupyter labextension install dask-labextension@1.1.0
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install @bokeh/jupyter_bokeh

##set -e
##set -x

## install jupyter labextensions
##jupyter labextension install --clean \
##    @jupyter-widgets/jupyterlab-manager \
##    dask-labextension \
##    @jupyterlab/geojson-extension jupyterlab-drawio
    
## add dask config
##mkdir -p ${KERNEL_PYTHON_PREFIX}/dask
##cd ../..
##cp dask_config.yaml ${KERNEL_PYTHON_PREFIX}/dask/dask.yaml
